---
title: "Group Measurements"
output: pdf_document
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}
# Process Data sets
# Taken from Peter S.

library(tidyverse)
process_state_data <- function(state_name, data_file, locations_file, 
                               filters_file = "filters.csv", 
                               measures_file = "measures.csv") {
  # Construct file paths 
  data_path <- file.path("../data/raw", paste0(state_name, "_State_Data"), data_file)
  locations_path <- file.path("../data/raw", paste0(state_name, "_State_Data"), locations_file)
  filters_path <- file.path("../data/raw", paste0(state_name, "_State_Data"), filters_file)
  measures_path <- file.path("../data/raw", paste0(state_name, "_State_Data"), measures_file)
  
  # Read in each data frame
  data_years <- read_csv(data_path)
  locations <- read_csv(locations_path)
  filters <- read_csv(filters_path)
  measures <- read_csv(measures_path)
  
  # Left join all of them
  data_comb <- data_years %>%
    left_join(locations, by = join_by(location_id == id)) %>%
    left_join(filters, by = join_by(filter_id == id)) %>%
    left_join(measures, by = join_by(measure_id == id)) %>%
  # Rename appropriate cols as well
    rename(
      location_type = type,
      location_name = name.x,
      measure_name = name.y,
      measure_format = format,
      demographics = description ## This is what encodes lawyer type (from filters.csv)
    ) %>%
  # Reorder ids to be next to descriptions
    ## Measure filter location
    select(
      measure_id, measure_name, measure_format, #Measures
      filter_id, demographics, #filters
      location_id, location_type, location_name, #locations
      everything() #Everything else
    )
  
  return(data_comb)
}

# Process each state
data_pa_comb <- process_state_data("Pennsylvania", "data-2009-2013.csv", "locations.csv")
data_or_comb <- process_state_data("Oregon", "data-2009-2013-or.csv", "locations-or.csv")
data_fl_comb <- process_state_data("Florida", "data-2009-2013-fl.csv", "locations-fl.csv")
```



# Combine Measures
```{r}
pa_measures <- read.csv('../data/raw/Pennsylvania_State_Data/measures.csv') 
fl_measures <- read.csv('../data/raw/Florida_State_Data/measures.csv') 
or_measures <- read.csv('../data/raw/Oregon_State_Data/measures.csv') 


measures <- full_join(pa_measures, fl_measures, by = c("id", "name","format")) %>% 
  full_join(or_measures, fl_measures, by = c("id", "name","format","calculation"))
```

