---
title: "reg_counsel_type_pct"
output: html_document
---

# Taken from Peter S
# Load Data
```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, tidy = TRUE, tidy.opts = list(width.cutoff = 60))

knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.align="center",
               echo=FALSE)
```

```{r}
library(dplyr)
library(ggrepel)
library(stargazer)
library(tidyverse)
library(ggplot2)
library(tidyr)

library(bestglm)
library(stargazer)
library(car)
```

```{r}

```


# First Analysis 

## What are the different county variables that effect the conviction rates of different defendant types 
```{r}
locations_pa <- read_csv("../../data/raw/Pennsylvania_State_Data/locations.csv")
locations_or <- read_csv("../../data/raw/Oregon_State_Data/locations-or.csv")
locations_fl <- read_csv("../../data/raw/Florida_State_Data/locations-fl.csv")

rdf<-read.csv("../../Data/county_characteristics_conviction.csv")

rdf <- rdf %>% 
  mutate(Log.pop = log(Population),
         Log.urban = log(Urban.Population+1),
         Log.rural = log(Rural.Population+1),
         Log.Largest.Municipality.Population = log(Largest.Municipality.Population+1))

rdf_PA <- rdf %>% 
  filter(state == "PA") %>% 
  left_join(locations_pa, by = c("location_id" = "id"))
  
  
rdf_OR <- rdf %>% 
  filter(state == "OR") %>% 
  left_join(locations_or, by = c("location_id" = "id"))
  
rdf_FL <-rdf %>% 
  filter(state == "FL") %>% 
  left_join(locations_fl, by = c("location_id" = "id"))

#names(rdf_PA)

#max(car::logit(rdf_PA$Public.Defender.conviction.rate))
```

```{r}
process_state_data <- function(state_name, data_file, locations_file, 
                               filters_file = "filters.csv", 
                               measures_file = "measures.csv") {
  # Construct file paths 
  data_path <- file.path("../../data/raw", paste0(state_name, "_State_Data"), data_file)
  locations_path <- file.path("../../data/raw", paste0(state_name, "_State_Data"), locations_file)
  filters_path <- file.path("../../data/raw", paste0(state_name, "_State_Data"), filters_file)
  measures_path <- file.path("../../data/raw", paste0(state_name, "_State_Data"), measures_file)
  
  # Read in each data frame
  data_years <- read_csv(data_path)
  locations <- read_csv(locations_path)
  filters <- read_csv(filters_path)
  measures <- read_csv(measures_path)
  
  # Left join all of them
  data_comb <- data_years %>%
    left_join(locations, by = join_by(location_id == id)) %>%
    left_join(filters, by = join_by(filter_id == id)) %>%
    left_join(measures, by = join_by(measure_id == id)) %>%
  # Rename appropriate cols as well
    rename(
      location_type = type,
      location_name = name.x,
      measure_name = name.y,
      measure_format = format,
      demographics = description ## This is what encodes lawyer type
    ) %>%
  # Reorder ids to be next to descriptions
    ## Measure filter location
    select(
      measure_id, measure_name, measure_format, #Measures
      filter_id, demographics, #filters
      location_id, location_type, location_name, #locations
      everything() #Everything else
    )
  
  return(data_comb)
}

# Process each state
data_pa_comb <- process_state_data("Pennsylvania", "data-2009-2013.csv", "locations.csv")
data_or_comb <- process_state_data("Oregon", "data-2009-2013-or.csv", "locations-or.csv")
data_fl_comb <- process_state_data("Florida", "data-2009-2013-fl.csv", "locations-fl.csv")


```
```{r}
percent_att_type_df <- function(data_comb) {
  data_comb %>% filter(location_type == "county", measure_id == 120) %>%
    group_by(location_id) %>%
    mutate(
      # race of defendant
      # percent_afr_am = denominator[demographics == "African American defendants"]/
      #   denominator[demographics== "all defendants"],
      # percent_white = denominator[demographics == "white defendants"]/
      #   denominator[demographics== "all defendants"],
      # sex of defendant
      # percent_female = denominator[demographics == "female defendants"]/
      # denominator[demographics== "all defendants"],
      # types of defendant 
      percent_p = denominator[demographics == "defendants represented by private attorney"]/
        denominator[demographics== "all defendants"],
      percent_pd = denominator[demographics == "defendants represented by public defender"]/
        denominator[demographics== "all defendants"],
      percent_ca = denominator[demographics == "defendants represented by a court-appointed private attorney"]/
        denominator[demographics== "all defendants"],
      percent_sr = denominator[demographics == "defendants who self-represented"]/
        denominator[demographics== "all defendants"]
      ) %>% 
    distinct(location_id, .keep_all = TRUE) %>% 
    select(location_id, percent_p, percent_pd, percent_ca, percent_sr)
}

pct_att_type_pa <- percent_att_type_df(data_pa_comb)
pct_att_type_or <- percent_att_type_df(data_or_comb)
pct_att_type_fl <- percent_att_type_df(data_fl_comb)

full_pct_df_PA <- inner_join(rdf_PA, pct_att_type_pa, by ="location_id")
full_pct_df_OR <- inner_join(rdf_OR, pct_att_type_or, by ="location_id")
full_pct_df_FL <- inner_join(rdf_FL, pct_att_type_fl, by ="location_id")

```



```{r}

#PA
lm_pd_PA <- lm(
  car::logit(percent_pd) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Number.of.Criminal.Court.Judges + Police.Officers.per.100.000.Residents + Number.of.Full.Time.Prosecutors, 
  data   = full_pct_df_PA,
  na.action = na.omit)
#summary(lm_pd_PA)
#vif(lm_pd_PA)

lm_p_PA <- lm(
  car::logit(percent_p) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Number.of.Criminal.Court.Judges + Police.Officers.per.100.000.Residents + Number.of.Full.Time.Prosecutors, 
  data   = full_pct_df_PA,
  na.action = na.omit)
#summary(lm_p_PA)
#vif(lm_p_PA)

lm_ca_PA <- lm(
  car::logit(percent_ca) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Number.of.Criminal.Court.Judges + Police.Officers.per.100.000.Residents + Number.of.Full.Time.Prosecutors, 
  data   = full_pct_df_PA,
  na.action = na.omit)
#summary(lm_ca_PA)
#vif(lm_ca_PA)

lm_sr_PA <- lm(
  car::logit(percent_sr) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Number.of.Criminal.Court.Judges + Police.Officers.per.100.000.Residents + Number.of.Full.Time.Prosecutors, 
  data   = full_pct_df_PA,
  na.action = na.omit)
#summary(lm_sr_PA)
#vif(lm_sr_PA)
```

```{r, warning = FALSE, eval = FALSE}
# Selected som vars for visualization

rdf_PA %>%
  dplyr::select(Below.Poverty.Line, Public.Defender.conviction.rate, Private.conviction.rate,
                Court.Appointed.conviction.rate, Self.Represented.conviction.rate) %>%
  pivot_longer(-Below.Poverty.Line, names_to = "Type", values_to = "Rate") %>%
  ggplot(aes(x = Below.Poverty.Line, y = Rate)) +
  geom_point() +
  geom_smooth(method = "loess", se = TRUE, color = "red") +
  facet_wrap(~ Type, scales = "free_y") +
  labs(title = "Pennsylvania: Conviction Rate vs Poverty Rate",
       x = "Below Poverty Line", y = "Conviction Rate")
```

```{r}
# OR
lm_pd_OR<- lm(
  car::logit(percent_pd) ~ 
    # Population
    Log.pop + Young.Males.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate ,
    # Criminal Justice
    # NONE
  data   = full_pct_df_OR,
  na.action = na.omit)
#summary(lm_pd_OR)
#vif(lm_pd_OR)

lm_p_OR<- lm(
  car::logit(percent_p) ~ 
    # Population
    Log.pop + Young.Males.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate ,
    # Criminal Justice
    # NONE
  data   = full_pct_df_OR,
  na.action = na.omit)
#summary(lm_p_OR)
#vif(lm_p_OR)


lm_ca_OR<- lm(
  car::logit(percent_ca) ~ 
    # Population
    Log.pop + Young.Males.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate ,
    # Criminal Justice
    # NONE
  data   = full_pct_df_OR,
  na.action = na.omit)
#summary(lm_ca_OR)
#vif(lm_ca_OR)


lm_sr_OR <- lm(
  car::logit(percent_sr) ~ 
    # Population
    Log.pop + Young.Males.Population +
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate ,
    # Criminal Justice
    # NONE
  data   = full_pct_df_OR,
  na.action = na.omit)
#summary(lm_sr_OR)
#vif(lm_sr_OR)
```

```{r, warning = FALSE, eval = FALSE}
# Selected som vars for visualization

rdf_PA %>%
  dplyr::select(Log.pop, High.School.Graduates) %>%
  pivot_longer(-Log.pop, names_to = "Type", values_to = "Rate") %>%
  ggplot(aes(x = Log.pop, y = Rate)) +
  geom_point() +
  geom_smooth(method = "loess", se = TRUE, color = "red") +
  facet_wrap(~ Type, scales = "free_y") +
  labs(title = "Pennsylvania: Conviction Rate vs Log Population",
       x = "Log Population", y = "Conviction Rate")
```


```{r}
# FL
lm_pd_FL<- lm(
  car::logit(percent_pd) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Police.Officers.per.100.000.Residents,
  data   = full_pct_df_FL,
  na.action = na.omit)
#summary(lm_pd_FL)
#vif(lm_pd_FL)

lm_p_FL <- lm(
  car::logit(percent_p) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Police.Officers.per.100.000.Residents,
  data   = full_pct_df_FL,
  na.action = na.omit)
#summary(lm_p_FL)
#vif(lm_p_FL)


lm_ca_FL<- lm(
  car::logit(percent_ca) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Police.Officers.per.100.000.Residents,
  data   = full_pct_df_FL,
  na.action = na.omit)
#summary(lm_ca_FL)
#vif(lm_ca_FL)

lm_sr_FL <- lm(
  car::logit(percent_sr) ~ 
    # Population
    Log.pop + Young.Males.Population + #Log.Largest.Municipality.Population + 
    # Racial/Ethnicity
    African.American.Population + Native.American.Alaskan.Population + 
    Asian.or.Pacific.Islander.Population + Hispanic.or.Latino.Population +
    # Econ
    Below.Poverty.Line + Unemployment.Rate +
    # Criminal Justice
    Police.Officers.per.100.000.Residents,
  data   = full_pct_df_FL,
  na.action = na.omit)
#summary(lm_sr_FL)
#vif(lm_sr_FL)
```


# Summary Tables
```{r, eval=FALSE}
summary(lm_pd_PA)
summary(lm_p_PA)
summary(lm_ca_PA)
summary(lm_sr_PA)

```
```{r, eval=FALSE}
summary(lm_pd_OR)
summary(lm_p_OR)
summary(lm_ca_OR)
summary(lm_sr_OR)

```
```{r, eval=FALSE}
summary(lm_pd_FL)
summary(lm_p_FL)
summary(lm_ca_FL)
summary(lm_sr_FL)
```

# Coefficient Tables
```{r}
library(stargazer)

state_coef_table <- function(state, lm_pd, lm_p, lm_ca, lm_sr, covar_labels, state_name) {
  stargazer(
    lm_pd,
    lm_p,
    lm_ca,
    lm_sr,
    
    type = "text",
    title = paste0("Counsel Type Percentage Regression Results (",
                                  state_name,")"),
    
    dep.var.labels.include = FALSE,
    dep.var.caption = "",#Regression Results for Conviction Rates by Counsel Type (Pennsylvania)",
    column.labels = c(
      "Public Defender",
      "Private",
      "Court Appointed",
      "Self-Represented"
    ),
    
    #dep.var.labels = "Logit(Conviction Rate)",
    
    digits = 3,
    report = "vc*s",
    omit.stat = c("f", "rsq", "ser"),

    covariate.labels = covar_labels,
    
    align = TRUE
  ) 
}


covar_labels_PA = c("Log Population",
                    "Proportion of Young Males",
                    "Proportion African American",
                    "Proportion Native American / Alaskan",
                    "Proportion Asian / Pacific Islander",
                    "Proportion Hispanic or Latino",
                    "Poverty Rate",
                    "Unemployment Rate",
                    "Number of Criminal Court Judges",
                    "Police Officers per 100,000 Residents",
                    "Number of Full-Time Prosecutors"
)

covar_labels_OR = c("Log Population",
                    "Proportion of Young Males",
                    "Proportion African American",
                    "Proportion Native American / Alaskan",
                    "Proportion Asian / Pacific Islander",
                    "Proportion Hispanic or Latino",
                    "Poverty Rate",
                    "Unemployment Rate"#,
                    #"Number of Criminal Court Judges",
                    #"Police Officers per 100,000 Residents",
                    #"Number of Full-Time Prosecutors"
)

covar_labels_FL = c("Log Population",
                    "Proportion of Young Males",
                    "Proportion African American",
                    "Proportion Native American / Alaskan",
                    "Proportion Asian / Pacific Islander",
                    "Proportion Hispanic or Latino",
                    "Poverty Rate",
                    "Unemployment Rate",
                    #"Number of Criminal Court Judges",
                    "Police Officers per 100,000 Residents"#,
                    #"Number of Full-Time Prosecutors"
)

state_coef_table("pa", lm_pd_PA, lm_p_PA, lm_ca_PA, lm_sr_PA, covar_labels_PA, "Pennsylvania")
state_coef_table("or", lm_pd_OR, lm_p_OR, lm_ca_OR, lm_sr_OR, covar_labels_OR, "Oregon")
state_coef_table("fl", lm_pd_FL, lm_p_FL, lm_ca_FL, lm_sr_FL, covar_labels_FL, "Florida")
```

# PA Public Defender Residual Diagnostics
```{r, eval=FALSE}
# =========================
# Residual Diagnostics (PA - Public Defender)
# =========================

par(mfrow = c(2,2))

# 1. QQ plot (normality)
qqnorm(residuals(lm_pd_PA), main = "QQ Plot (PA - PD)")
qqline(residuals(lm_pd_PA), col = "red")

# 2. Residuals vs Fitted (linearity + homoskedasticity)
plot(fitted(lm_pd_PA), residuals(lm_pd_PA),
     main = "Residuals vs Fitted (PA - PD)",
     xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, col = "red")

# 3. Histogram of residuals
#hist(residuals(lm_pd_PA),
#     main = "Residual Histogram (PA - PD)",
#     xlab = "Residuals")

```

# Residual Disgnostics Function
```{r}
residual_diag_plots <- function (lm_att_state) {
  par(mfrow = c(2,2))
  qqnorm(residuals(lm_att_state), main = "QQ Plot")
  qqline(residuals(lm_att_state), col = "red")

  # 2. Residuals vs Fitted (linearity + homoskedasticity)
  plot(fitted(lm_att_state), residuals(lm_att_state),
       main = "Residuals vs Fitted",
       xlab = "Fitted Values", ylab = "Residuals")
  abline(h = 0, col = "red")
}

```
```{r, echo = TRUE}
residual_diag_plots(lm_pd_PA)
residual_diag_plots(lm_p_PA)
residual_diag_plots(lm_ca_PA)
residual_diag_plots(lm_sr_PA)

```
```{r, echo = TRUE}
residual_diag_plots(lm_pd_OR)
residual_diag_plots(lm_p_OR)
residual_diag_plots(lm_ca_OR)
residual_diag_plots(lm_sr_OR)

```
```{r, echo = TRUE}
residual_diag_plots(lm_pd_FL)
residual_diag_plots(lm_p_FL)
residual_diag_plots(lm_ca_FL)
residual_diag_plots(lm_sr_FL)
```

# PA Public Defender Leave-One-Out
```{r, eval=FALSE}
# =========================
# Leave-One-Out / Influence Analysis (PA - Public Defender)
# =========================

mod <- lm_pd_PA

# ---- Step 1: Identify outliers ----

# Studentized residuals (outliers in response)
rstud <- rstudent(mod)
outliers <- which(abs(rstud) > 2)

# Cook's distance (influential points)
cooks <- cooks.distance(mod)
threshold <- 4 / length(cooks)
influential <- which(cooks > threshold)

# Combine both
suspects <- unique(c(outliers, influential))

cat("Potential influential observations:\n")
print(suspects)

used_data <- model.frame(mod)
used_rows <- as.numeric(rownames(used_data))

suspect_info <- data.frame(
  obs = suspects,
  original_row = used_rows[suspects],
  location_id = rdf_PA$location_id[used_rows[suspects]],
  rstudent = round(rstud[suspects], 3),
  cooks_d = round(cooks[suspects], 3)
)
```

```{r, eval=FALSE}

# ---- Cook's Distance Plots ---#
# Cook's Distance Plot
plot(cooks,
     pch = 19,
     main = "Cook's Distance (PA Public Defender Model)",
     xlab = "Observation",
     ylab = "Cook's Distance")

abline(h = threshold, col = "red", lty = 2)

# label flagged points
text(suspects, cooks[suspects],
     labels = suspect_info$location_id,
     pos = 3, cex = 0.8)


# ---- Step 2: Leave-one-out refits ----

loo_models <- lapply(suspects, function(i) {
  lm(formula(mod), data = rdf_PA[-used_rows[i], , drop = FALSE],
     na.action = na.omit)
})

names(loo_models) <- paste0("remove_obs_", suspects)


# ---- Step 3: Compare coefficients ----

#original_coef <- coef(mod)

#cat("\nOriginal coefficients:\n")
#print(original_coef)

#cat("\nLeave-one-out coefficients:\n")
#print(lapply(loo_models, coef))


selected_indices <- seq_len(min(3, length(loo_models)))
selected_models <- loo_models[selected_indices]

```

```{r, eval=FALSE}
used_data <- model.frame(lm_pd_PA)
used_rows <- as.numeric(row.names(used_data))

suspect_info <- data.frame(
  obs = suspects, # row numbers in the model data
  location_id = rdf_PA$location_id[used_rows[suspects]],
  rstudent = rstud[suspects],
  cooks_d = cooks[suspects],
  row.names = NULL # row number in original dataset
)

suspect_info

vars_to_check <- c(
  "Log.pop",
  "Below.Poverty.Line",
  "Number.of.Criminal.Court.Judges"
)

# ---- Original coefficients ----
comparison_table <- data.frame(
  variable = vars_to_check,
  original = round(coef(lm_pd_PA)[vars_to_check], 3),
  row.names = NULL
)

# ---- Add LOO columns ----
for (j in seq_along(suspects)) {
  loc <- suspect_info$location_id[j]
  
  comparison_table[[paste0("remove_id_", loc)]] <- round(coef(loo_models[[j]])[vars_to_check], 3)
}

comparison_table


change_table <- data.frame(
  variable = vars_to_check
)

for (j in seq_along(suspects)) {
  loc <- suspect_info$location_id[j]
  
  change_table[[paste0("change_id_", loc)]] <-
    round(coef(loo_models[[j]])[vars_to_check] - coef(lm_pd_PA)[vars_to_check], 3) # LOO - Original
}

change_table

# reshape change_table to long format
change_long <- change_table %>%
  pivot_longer(-variable, names_to = "model", values_to = "change")

ggplot(change_long, aes(x = variable, y = change, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Coefficient Changes After Removing Influential Observations",
       x = "Variable",
       y = "Change in Coefficient") +
  theme_minimal()
```

# Cook's Distanse Plot
```{r}
cooks_plot <- function (mod, state, counsel) {
  # ---- Step 1: Identify outliers ----
  
  # Studentized residuals (outliers in response)
  rstud <- rstudent(mod)
  outliers <- which(abs(rstud) > 2)
  
  # Cook's distance (influential points)
  cooks <- cooks.distance(mod)
  threshold <- 4 / length(cooks)
  influential <- which(cooks > threshold)
  
  # Combine both
  # suspects <- unique(c(outliers, influential))
  # 
  # #cat("Potential influential observations:\n")
  # #print(suspects)
  # 
  used_data <- model.frame(mod)
  used_rows <- as.numeric(rownames(used_data))


  df <- data.frame(
    obs = 1:length(cooks),
    cooks = cooks,
    label = rdf_PA$name[used_rows]
  )
  
  ggplot(df, aes(x = obs, y = cooks)) +
    geom_point(color = "grey70") +
    geom_hline(yintercept = threshold, color = "red", linetype = "dashed") +
    geom_text_repel(
      data = df[influential, ],
      aes(label = label),
      size = 3
    ) +
    labs(
      title = paste0("Cook's Distance (", state, " - ", counsel, ") % Attourney Type"),
      x = "Observation",
      y = "Cook's Distance"
    ) +
    theme_minimal() +
    theme(axis.text.x  = element_blank(),
          axis.ticks.x = element_blank())
}

```
```{r, echo = TRUE}
cooks_plot(lm_pd_PA, "PA", "PD")
cooks_plot(lm_p_PA, "PA", "P")
cooks_plot(lm_ca_PA, "PA", "CA")
cooks_plot(lm_sr_PA, "PA", "SR")

```
```{r, echo = TRUE}
cooks_plot(lm_pd_OR, "OR", "PD")
cooks_plot(lm_p_OR, "OR", "P")
cooks_plot(lm_ca_OR, "OR", "CA")
cooks_plot(lm_sr_OR, "OR", "SR")

```
```{r, echo = TRUE}
cooks_plot(lm_pd_FL, "FL", "PD")
cooks_plot(lm_p_FL, "FL", "P")
cooks_plot(lm_ca_FL, "FL", "CA")
cooks_plot(lm_sr_FL, "FL", "SR")
```


# Ignore below
```{r, eval=FALSE}
change_table <- data.frame(
  variable = vars_to_check
)

for (j in seq_along(suspects)) {
  loc <- suspect_info$location_id[j]
  
  change_table[[paste0("remove_id_", loc)]] <-
    round(
      coef(loo_models[[j]])[vars_to_check] - coef(mod)[vars_to_check],
      3
    )
}

rownames(change_table) <- NULL

change_table
```

```{r, eval=FALSE}
("Pennsylvania", "data-2009-2013.csv", "locations.csv")
pa_data <- read_csv("../../Data/raw/Pennsylvania_State_Data/data-2009-2013.csv")

convic_pa <- pa_data %>% filter(measure_id == 120) %>% select(value)
convic_pa
min(convic_pa, na.rm = TRUE)
```
